version: "3.9"
services:
  postgres:
    image: postgres:14.1
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: recon
      POSTGRES_PASSWORD: "postgres"
    volumes:
    - pg_data:/var/lib/postgresql/data
  frontend:
    image: angular
    container_name: angular
    build:
      context: ./angular
    ports:
      - "9000:80"
  backend:
    image: spring-boot
    container_name: spring-boot
    build:
      context: ./spring-boot
    ports:
      - "4200:8080"
    depends_on:
      - postgres
volumes:
  pg_data: 